### ISSUE TITLE
Styling pages

### ISSUE THREAD

**Issue by GnarlyOcelot** [Treesearch/Treesearch#2]
- [x] **For the red/green containers**
    - [x] Look in this quotes-block [here](http://www.evolutionnews.org/2011/12/fact-checking_w053551.html). Add same faded red/green quotation-marks image to ALL red/green boxes, since they are all things one person or the other is saying.
- [ ] **Other**
    - [ ] Give me css magic for creating those green, red, and purple A, B, C, and 1, 2, 3. I can send you the images. 
    - [ ] Give me the ability to indent (and particularly _in very slight increments_). 
    - [x] Set page margins to be like to Drupal.
    - [x] Turn off the XS and XXS designator at the bottom-left of the screen (when shrinking the page).
   - [ ] Set up ability for me to RSS a Argument page   

- - - - - - -
- [ ] **Blog**
   - [ ] Set up RSS feed

- - - - - - -
- [ ] **Article** 
   - [x] Remove "Create Date: March 04 2015" etc.
   - [x] Add "citations" block to Article
   - [ ] Remove "Post on" from images  
- - - - - - - 
- [ ] Other
   - [ ] Remove comments from Gospel page
  - [ ] 

- - - - - - - -

**FINISHED**
- [x] **Set styles**
    - [x] Set [\<ref>] to this color gray: #A9A9A9
    - [x] Set [\<sup>] to superscript, **bold** and black
    - [x] Set [\<sup1>] to standard superscript
- [x] **Modify accordion link-text**
    - [x] For accordion links under Green/green, set link mouse-over to link-green/red.
- [X] For the gray source area:
    - [X] Set link-text to purple again (mouse-over for brighter purple).
    - [x] Make the list-numbers offset like in Drupal.

**Comment by ChaseGiunta** [comment]
sorry buddy, won't be able to help you with this stuff for a while. closing all for now.
