### ISSUE TITLE
Design Treesearch tree banner

### ISSUE THREAD

**Issue by GnarlyOcelot** [Treesearch/Treesearch#3]
- [ ] **Buttons/widgets for tree**
    - [ ] Add buttons for ‘About Belief Map,’ ‘Donate’
    - [ ] Add sexy search bar
- [x] **Change logo to Belief-Map**
- [ ] **Fix image size on Safari?**
![screen shot 2015-04-03 at 11 35 14 am](https://cloud.githubusercontent.com/assets/6185615/6985173/10a79e84-d9f6-11e4-8f2f-f27e8d366803.png)

**Comment by ChaseGiunta** [comment]
sorry buddy, won't be able to help you with this stuff for a while. closing all for now.
